# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_payment_txn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to=b'avatars'),
        ),
    ]
